name: Periodic Python Script

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install instaloader

      - name: Run Python script
        run: |
          python script.py
